let dados = [
    {
      Titulo: "Cidade dos Anjos",
      Ano: "1998",
      Diretor: "Brad Silberling",
      Elenco: "Nicolas Cage, Meg Ryan, Andre Braugher",
      Sinopse: "Um anjo na Terra, um médico incapaz de acreditar, um paciente com um segredo, uma história de amor feita no céu.",
      Genero: "Tragédia, romance, fantasia, drama",
      ImdbRating: "6,7"
    },
    {
      Titulo: "Arizona Nunca Mais",
      Ano: "1987",
      Diretor: "Joel Coen, Ethan Coen",
      Elenco: "Nicolas Cage, Holly Hunter, Trey Wilson",
      Sinopse: "Quando um casal sem filhos decide ajudar um dos filhos de outra família, suas vidas se tornam mais complicadas do que eles esperavam.",
      Genero: "Comédia, Crime",
      ImdbRating: "7,3",
    },
    {
      Titulo: "Sonhos Rebeldes",
      Ano: "1983",
      Diretor: "Martha Coolidge",
      Elenco: "Nicolas Cage, Deborah Foreman, Elizabeth Daily",
      Sinopse: "Julie, uma garota do vale, conhece Randy, um punk da cidade. Eles são de mundos diferentes e encontram o amor. ",
      Genero: "Coming of age, Comédia Romantica, Comédia Adolecente, Romance",
      ImdbRating: "6,4",
    },
    {
      Titulo: "O Selvagem da Motocicleta",
      Ano: "1983",
      Diretor: "Francis Ford Coppola",
      Elenco: "Nicolas Cage, Matt Dillon, Mickey Rourke, Diane Lane",
      Sinopse: "Rusty James, um bandido de rua, luta para estar à altura da reputação de seu lendário irmão, e tem saudades dos dias em que a guerra de gangues estava acontecendo.",
      Genero: "Drama, Crime, Romance, Coming of Age",
      ImdbRating: "7,1",
    },
    {
      Titulo: "Adeus à Inocência",
      Ano: "1984",
      Diretor: "Richard Benjamin",
      Elenco: "Nicolas Cage, Sean Penn",
      Sinopse: "Dois fuzileiros navais tentam aproveitar o tempo que lhes resta antes de seguirem sua jornada para a Segunda Guerra Mundial.",
      Genero: "Comédia, Drama, Romance",
      ImdbRating: "6,6",
    },
    {
      Titulo: "Cotton Club",
      Ano: "1984",
      Diretor: "Francis Ford Coppola",
      Elenco: "Nicolas Cage, Richard Gere, Diane Lane",
      Sinopse: "Conheça os músicos de jazz, dançarinos, proprietários e convidados do Cotton Club em Harlem de 1928 a 1930.",
      Genero: "Crime, Drama, Musica",
      ImdbRating: "6,5",
    },
    {
      Titulo: "Asas da Liberdade",
      Ano: "1984",
      Diretor: "Alan Parker",
      Elenco: "Nicolas Cage, Matthew Modine",
      Sinopse: "Depois que dois amigos voltam para casa da Guerra do Vietnã, um deles se torna mentalmente instável e obcecada em se tornar um pássaro.",
      Genero: "Drama, Guerra",
      ImdbRating: "7,2",
    },
    {
      Titulo: "O Homem dos Sonhos",
      Ano: "2023",
      Diretor: "Kristoffer Borgli",
      Elenco: "Nicolas Cage, Lily Bird",
      Sinopse: "Um infeliz pai de família vê sua vida virar de cabeça para baixo quando milhões de estranhos começam a vê-lo em seus sonhos. ",
      Genero: "Drama, Comédia sombria, fantasia, horror",
      ImdbRating: "6,9",
    },
    {
      Titulo: "Longlegs: Vínculo Mortal",
      Ano: "2024",
      Diretor: "Osgood Perkins",
      Elenco: "Nicolas Cage, Maika Monroe",
      Sinopse: "Uma agente do FBI é designada para um caso envolvendo um assassino em série impiedoso. ",
      Genero: "Horror, terror psicológico, thriller, suspense, crime",
      ImdbRating: "6,8",
    },
    {
      Titulo: "Renfield - Dando Sangue Pelo Chefe",
      Ano: "2023",
      Diretor: "Chris Mckay",
      Elenco: "Nicolas Cage, Nicholas Hoult",
      Sinopse: "Renfield, o fiel servo do Conde Drácula, tenta se libertar de seu vínculo mortal.",
      Genero: "Comédia, Terror, Dark Comedy, Ação",
      ImdbRating: "6,4",
    },
    {
      Titulo: "The Flash",
      Ano: "2022",
      Diretor: "Andy Muschietti",
      Elenco: "Nicolas Cage, Ezra Miller",
      Sinopse: "O velocista escarlate atravessa o multiverso para salvar o futuro.",
      Genero: "Ação, Aventura, fantasia, super-heroi",
      ImdbRating: "6,6",
    },
    {
      Titulo: "O Peso do Talento",
      Ano: "2021",
      Diretor: "Tom Gormican",
      Elenco: "Nicolas CagePedro Pascal",
      Sinopse: "Nicolas Cage, interpretando a si mesmo, é forçado a aceitar um papel inusitado.",
      Genero: "Comédia, Ação, buddy comedy",
      ImdbRating: "7.0",
    },
    {
      Titulo: "Willy’s Wonderland: Parque Maldito",
      Ano: "2021",
      Diretor: "Kevin Lewis",
      Elenco: "Nicolas Cage, Emily Tosta",
      Sinopse: "Um zelador enfrenta criaturas animatrônicas mortais em um parque abandonado.",
      Genero: "Terror, ação, suspense, comédia ",
      ImdbRating: "5,5",
    },
    {
      Titulo: "PIG - A Vingança",
      Ano: 2020,
      Diretor: "Michael Sarnoski",
      Elenco: "Nicolas Cage, Alex Wolff",
      Sinopse: "Um caçador de trufas parte em uma jornada para encontrar seu porco roubado.",
      Genero: "Drama, mistério",
      ImdbRating: "6,9",
    },
    {
      Titulo: "Motoqueiro Fantasma: Espírito de Vingança",
      Ano: "2011",
      Diretor: "Mark Neveldine, Brian Taylor",
      Elenco: "Nicolas Cage, Idris Elba",
      Sinopse: "Johnny Blaze, torturado pela maldição do Motoqueiro Fantasma, tem uma chance de redenção ao proteger o filho do Diabo, cujo pai o está perseguindo.",
      Genero: "Super-heroi, fantasia, ação, thriller",
      ImdbRating: "4,3",
    },
    {
      Titulo: "O Senhor das Armas",
      Ano: "2005",
      Diretor: "Andrew Niccol",
      Elenco: "Nicolas Cage, Ethan Hawke, Jared Leto",
      Sinopse: "Um traficante de armas confronta o moral de seu trabalho enquanto é perseguido por um agente da Interpol.",
      Genero: "Drama, crime, true crime",
      ImdbRating: "7,6",
    },
    {
      Titulo: "O Aprendiz de Feiticeiro",
      Ano: "2010",
      Diretor: "Jon Turteltaub",
      Elenco: "Nicolas Cage, Jay Baruchel, Alfred Molina",
      Sinopse: "O mestre feiticeiro Balthazar Blake deve encontrar e treinar o descendente de Merlin para derrotar Morgana la Fée, a feiticeira das trevas.",
      Genero: "Ação, fantasia, aventura",
      ImdbRating: "6,1",
    },
    {
      Titulo: "Kick-Ass: Quebrando Tudo",
      Ano: "2010",
      Diretor: "Matthew Vaughn",
      Elenco: "Nicolas Cage, Aaron Taylor-Johnson, Chloë Grace Moretz",
      Sinopse: "Dave Lizewski é um estudante do ensino médio e fã de quadrinhos, que um dia decide se tornar um super-herói, mesmo que ele não tenha nenhum poder, treinamento ou motivos significativos para fazê-lo.",
      Genero: "Ação, super-heroi, comédia, drama, crime",
      ImdbRating: "7,6",
    },
    {
      Titulo: "Vivendo no Limite",
      Ano: "1999", 
      Diretor: "Martin Scorsese",
      Elenco: "Nicolas Cage, Patricia Arquette, John Goodman",
      Sinopse: "Perseguido pelos pacientes que ele não pôde salvar, um paramédico de Manhattan luta para manter sua sanidade por três noites turbulentas e agitadas.",
      Genero: "thriller, drama",
      ImdbRating: "6,9",
    },
    {
      Titulo: "A Outra Face",
      Ano: "1997",
      Diretor: "John Woo",
      Elenco: "John Travolta, Nicolas Cage, Joan Allen",
      Sinopse: "Para frustrar uma conspiração terrorista, um agente do FBI passa por uma cirurgia de transplante de rostro e assume a identidade de um terrorista.",
      Genero: "Ação, crime, sci-fu, thriller",
      ImdbRating: "7,3",
    },
    {
      Titulo: "Ajuste de Contas",
      Ano: "2019",
      Diretor: "Shawn Ku",
      Elenco: "Nicolas Cage, Benjamin Bratt",
      Sinopse: "Um ex-prisioneiro busca vingança contra seu antigo mentor.",
      Genero: "Ação, Drama, thriller",
      ImdbRating: "2,5",
    },
    {
        Titulo: "Despedida em Las Vegas",
        Ano: "1995",
        Diretor: "Mike Figgis",
        Elenco: "Nicolas Cage, Julian Sands",
        Sinopse: "Um roteirista alcoólatra se muda para Las Vegas para beber até morrer e inicia um relacionamento com uma prostituta.",
        Genero: "Drama, Romance",
        ImdbRating: "7.5",
    },
]
  